### ISSUE TITLE
Allow API to update DNS object

### ISSUE THREAD

**Issue by sauloal** [roaldnefs/python-transip#36]
**Is your feature request related to a problem? Please describe.**
I want do update an existing DNS key

**Describe the solution you'd like**
Implement the update function for DNS

**Describe alternatives you've considered**
- Call the API directly

**Additional context**
I need to be able to delete/update DNS keys in order to automatically run Let'sEncrypt certbot

**Comment by roaldnefs** [comment]
I've just merged #40 to allow DNS record(s) to be updated, will be making a new release within a few minutes.

For instructions on updating a single DNS record,  see: https://github.com/roaldnefs/python-transip#update-single-dns-entry.
For instructions on updating all DNS records at once, see: https://github.com/roaldnefs/python-transip#update-all-dns-entries-for-a-domain.

**Comment by roaldnefs** [comment]
Options to update and delete DNS records are available in `python-transip>=0.4.0`.

**Comment by sauloal** [comment]
Can't thank you enough for the quick response!

**Comment by sauloal** [comment]
Hello @roaldnefs .
I've tested today and it works as expected.
The documentation is incorrect though:

[Update single DNS entry](https://python-transip.readthedocs.io/en/latest/#id39)
says to use
`domain.update(dns_entry_data)`

and [Remove a DNS entry from a domain](domain.update(dns_entry_data))
says to use
`domain.delete(dns_entry_data)` which does not work.

```python
Traceback (most recent call last):
  File "tip.py", line 107, in deleteDnsEntry
    domain.delete(data)
  File "/usr/local/lib/python3.8/dist-packages/transip/base.py", line 46, in __getattr__
    raise AttributeError(name)
AttributeError: delete
```

**Comment by roaldnefs** [comment]
Thanks for the feedback @sauloal! I've updated the documentation in #42.
