### ISSUE TITLE
The testuser

### ISSUE THREAD

**Issue by keestux** [roaldnefs/python-transip#53]
I just found this package and I was briefly going through it (including the tests). I saw the "testuser" with its private key. I was wondering if this is a test user (and key) supplied by TransIP. I couldn't find it in their API documentation. I'm just trying to figure out how this works.

**Comment by roaldnefs** [comment]
The `testuser` and its private key are only used in the mocked API calls.

The TransIP API does allow users to use a [demo token](https://api.transip.nl/rest/docs.html#header-demo-token) to authenticate as the TransIP demo user in test mode. The demo token can directly be imported from `python-transip`, e.g.:

```python
import transip
from transip.v6 import DEMO_TOKEN

# You can initialize a TransIP client using an access token directly.
client = transip.TransIP(access_token=DEMO_TOKEN)
```
